# Generated by Django 2.1.5 on 2019-02-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190210_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
    ]
