# Generated by Django 2.1.5 on 2019-02-12 03:00

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190212_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(default=1, max_length=128, verbose_name='Address lines 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address lines 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(default='FL', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='Zipcode'),
        ),
    ]
