# Generated by Django 2.1.5 on 2019-02-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190212_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.PositiveIntegerField(choices=[(1, 'Home address'), (2, 'Shipping address')])),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Miami', max_length=60),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Florida', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='33165', max_length=5),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(through='users.AddressInfo', to='users.Address'),
        ),
    ]
