# Generated by Django 2.1.5 on 2019-02-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190227_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresstype',
            options={'verbose_name': 'Type of Address', 'verbose_name_plural': 'Type of Address'},
        ),
    ]
