# Generated by Django 2.1.5 on 2019-02-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190227_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
            preserve_default=False,
        ),
    ]
