# Generated by Django 2.1.5 on 2019-02-27 23:20

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190227_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresstype',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addresstype',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(default=1, max_length=128, verbose_name='Address lines 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address lines 2'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(default='FL', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='Zipcode'),
        ),
        migrations.DeleteModel(
            name='AddressType',
        ),
    ]
