# Generated by Django 2.1.5 on 2019-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190228_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(to='users.Address'),
        ),
    ]
