# Generated by Django 2.1.5 on 2019-02-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190228_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
