# Generated by Django 2.1.5 on 2019-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_profile_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(to='users.Address'),
        ),
    ]
