# Generated by Django 2.1.5 on 2019-02-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190228_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Address'),
        ),
    ]
