# Generated by Django 2.1.5 on 2019-02-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190228_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
    ]
