# Generated by Django 2.1.5 on 2019-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20190228_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
