# Generated by Django 2.1.5 on 2019-02-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_profile_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Miami', max_length=60),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Florida', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='33165', max_length=5),
        ),
    ]
