# Generated by Django 2.1.5 on 2019-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookDetails', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
