# Generated by Django 2.1.5 on 2019-02-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('list_name', models.CharField(max_length=25)),
            ],
        ),
    ]
