# Generated by Django 2.1.5 on 2019-02-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20190223_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user_name',
        ),
    ]
