# Generated by Django 2.1.5 on 2019-02-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20190212_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wbooks',
            old_name='book_name',
            new_name='name',
        ),
    ]
