# Generated by Django 2.1.5 on 2019-02-12 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20190212_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='wbooks',
            name='wList_name',
        ),
        migrations.RenameModel(
            old_name='wLists',
            new_name='List',
        ),
        migrations.DeleteModel(
            name='wBooks',
        ),
        migrations.AddField(
            model_name='book',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.List'),
        ),
    ]
