# Generated by Django 2.1.5 on 2019-02-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20190212_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list_name',
            new_name='name',
        ),
    ]
