# Generated by Django 2.1.5 on 2019-02-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
    ]
